name: "\U0001F41B Bug Report"
description: "Report a reproducible bug"
labels: "needs review"
issue_body: true
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
- type: textarea
  attributes:
    label: Summary
    description: Describe the issue in 1 or 2 sentences
    placeholder: Clearly describe what the expected behavior is vs. what is actually happening. This should be as short as possible, while still communicating all the necessary information. If your summary is just 'X library/method isn't working', then you need to continue debugging yourself and provide more information.
  validations:
    required: true
- type: input
  attributes:
    label: Version
    description: What version of FluentValidation are you using?
- type: textarea
  attributes:
    label: Reproducible demo or steps to reproduce from a blank project
    description: "This should include as little code as possible, do not simply link your entire project."
  validations:
    required: true
- type: markdown
  attributes:
    value: Please make sure contributors can follow the steps your provided in order to reproduce the bug.
- type: markdown
  attributes:
    value: "**Realize that it is up to you to debug your code and be as certain as possible that the bug is with FluentValidation, not with your own app.** 